== Purpose
. Software package management of JBoss Enterprise Application Platform v6.1.1 on Red Hat Enterprise Linux (RHEL)
. This version of JBoss EAP 6 is used specifically to support Red Hat JBoss BPMS, BRMS and FSW.
. This RPM targets BPMS, BRMS and FSW in both OSE and traditional non-cloud, RHEL environments

== Problem:  JBoss EAP version in-compatibilities
. The RPMs in the jbappplatform RHN channel continously evolve and sys admins are free to upgrade thier environments as these upgrades to JBoss are released.
. Red Hat / JBoss BPMS and FSW have a hard-dependency on JBoss EAP 6.1.1.

== Alternatives
. *Use RPMs via jbappplatform channel but don't upgrade*
** Its technically feasible that a system administrator could elect to install JBoss EAP 6.1.1 and never upgrade
** This would nicely facilitate products such as BPMS, BRMS and FSW that have a hard dependency on this particular version of JBoss EAP.
** This approach would be problematic however for other products that prefer either older or more current versions of JBoss EAP6.

. *Multiple versions of JBoss EAP installed from RHN channels*
** OSE engineering is apparently working with JBoss engineering to allow for multiple versions of JBoss EAP to be installed on an OSE node via RHN channels.
** so its concievable that at some point, a BPMS or FSW cartridge could specify a hard-dependency on for example:  JBoss EAP 6.1.1. 
** In this scenario, JBoss EAP 6.1.1 would be co-located in some manner with other versions of JBoss EAP on the same OSE node.
** Not quite sure what the time-line is for this feature to be rolled out in RHEL and Openshift

. *Stuff everything in an Openshift "Downloadable" cartridge*
** Openshift supports "downloadable" cartridges.
** It is technically possible that this cartridge could bundle both JBoss EAP6.1.1 plus BPMS6
** The problem with this approach is :
.. size of download makes for a long, network intensive experience to provision an OSE application
.. once downloaded, the size of the contents included in this cartridge count against cgroups disk quota allocated by OSE
*** one of the goals of this BPMS6 cartridge is to ensure that it fits comfortably in a medium-sized Openshift gear.
** Subsequently, this approach is impractical for OSE environments hosting typical JBoss payloads such BPMS and FSW.



== Solution
  - The purpose of this RPM is to package the specific version of JBoss EAP to support BPMS, BRMS and FSW.
  - When installed, this RPM will place JBoss EAP in:  /opt/jboss-bpm-soa/jboss-eap-6.1 .
  - No other files are installed via this RPM anywhere else on the operating system.
  - This JBoss EAP will not conflict with the JBoss EAP from the jbappplatform in any way, either at installation nor at runtime.
  - A 5G /opt partition is sufficient to support this RPM along with BPMS, FSW RPMs that layer on top



== Proposed Architecture
* link:https://raw.github.com/jboss-gpe-ose/jboss_bpm_soa_rpmbuild/master/SOURCES/jboss_bpm_soa_package_mgmt.png[SOURCES/jboss_bpm_soa_package_mgmt.png] provides an illustration of where this RPM fits into a software configuration architecture to support BPMS, BRMS and FSW.
* it's proposed that the RPM from this project, jboss_bpm_soa, be included in the existing jbappplatform channel from RHN
* the contents of this jboss_bpm_soa rpm installs in:  /opt/jboss_bpm_soa
* it's also proposed that the following channels be created and maintained in RHN:
. jboss_brms
** if a customer has purchased a subscription to BRMS, then that customer receives entitlements to this channel
** this channel will include RPMs that layer BRMS modules into /opt/jboss_bpm_soa/jboss-eap-6.1
.  jboss_bpms
** if a customer has purchased a subscription to BPMS, then that customer receives entitlements to this channel
** this channel will include RPMs that layer BPMS modules into /opt/jboss_bpm_soa/jboss-eap-6.1
** RPMs are also included that contain exploded business-central and dashbuilder web archives
.  jboss_fsw
** if a customer has purchased a subscription to FSW, then that customer receives entitlements to this channel
** this channel will include RPMs that layer FSW modules into /opt/jboss_bpm_soa/jboss-eap-6.1
** RPMs are also included that contain exploded overlord and bpel web archives


== Build Procedure
* NOTE:  built RPMs of this and related projects can be found link:http://people.redhat.com/jbride/ose/INSTALL.txt[here]
* If you are still interested in leveraging this project to build your own RPMs, then the following applies: 
. clone this project from github
. cd /path/to/this/jboss_bpm_soa_rpmbuild
. cp /path/to/jboss-eap-6.1.1.zip SOURCES
. rpmbuild --define "_sourcedir `pwd`/SOURCES" -ba SPECS/jboss_bpm_soa.spec
. rpm -qlp ~/rpmbuild/RPMS/x86_64/jboss_bpm_soa-6.1.1-1.el6.x86_64.rpm
. sudo rpm -ivh ~/rpmbuild/RPMS/x86_64/jboss_bpm_soa-6.1.1-1.el6.x86_64.rpm
. sudo rpm -e jboss_bpm_soa

== TO-DO
.  add documentation to /usr/share/doc 
